# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\xad\x02\n\x07Message\x12#\n\x07\x61llData\x18\x01 \x01(\x0b\x32\x10.Message.AllDataH\x00\x12\'\n\tbriefData\x18\x02 \x01(\x0b\x32\x12.Message.BriefDataH\x00\x1a\x61\n\x07\x41llData\x12\x11\n\ttimePoint\x18\x01 \x02(\x04\x12\x13\n\x0b\x63hannelData\x18\x02 \x03(\r\x12\x16\n\x0e\x63hannelAStarts\x18\x03 \x03(\r\x12\x16\n\x0e\x63hannelBStarts\x18\x04 \x03(\r\x1a\x66\n\tBriefData\x12\x11\n\ttimePoint\x18\x01 \x02(\r\x12\x0e\n\x06\x61Means\x18\x02 \x03(\x02\x12\x0e\n\x06\x62Means\x18\x03 \x03(\x02\x12\x12\n\naStandards\x18\x04 \x03(\x02\x12\x12\n\nbStandards\x18\x05 \x03(\x02\x42\t\n\x07message')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=18
  _globals['_MESSAGE']._serialized_end=319
  _globals['_MESSAGE_ALLDATA']._serialized_start=107
  _globals['_MESSAGE_ALLDATA']._serialized_end=204
  _globals['_MESSAGE_BRIEFDATA']._serialized_start=206
  _globals['_MESSAGE_BRIEFDATA']._serialized_end=308
# @@protoc_insertion_point(module_scope)
